movieapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = 'movieapp'
urlpatterns = [

    path('', index, name='index'),
    path('movie/<int:movie_id>/', detail, name='detail'),
    path('add/', add_movie, name='add_movie'),
    path('update/<int:id>/', update, name='update'),
    path('delete/<int:id>/', delete, name='delete')

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('movieapp.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    id = models.BigAutoField(
        primary_key=True
    )
    name = models.CharField(
        max_length=250,
        verbose_name="Moive name"
    )
    desc = models.TextField(
        verbose_name="Description"
    )
    year = models.PositiveBigIntegerField(
        verbose_name="release year"
    )
    image = models.ImageField(
        upload_to='gallery',
        verbose_name="Images"
    )
    director = models.CharField(
        max_length=100
    )
    

movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'image' , 'director']
        widgets={

            'name': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':"Enter movie name"
                }
            ),
            'desc': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':"Enter movie description",
                    'rows':4
                }
            ),
            'year': forms.NumberInput(
                attrs={
                    'class':'form-control',
                    'placeholder':"Enter movie year",
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class':'form-control-file',
                }
            ),
            'director': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':"Enter director name",
                }
            ),
            

        }

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect , get_object_or_404

from .forms import MovieForm
from .models import Movie


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }

    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': movie})


def add_movie(request):
    context={}
    if request.method == 'GET':
        context['form'] = MovieForm()
        return render(request , 'add.html' , context)
    
    elif request.method == 'POST':
        form = MovieForm(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        context['form'] = form
        return render(request , 'add.html' , context)


        

def update(request, id):
    context={}
    movieByid = get_object_or_404(Movie,pk=id)
    if request.method == 'GET':   
        context['form'] = MovieForm(instance=movieByid)
        return render(request , 'edit.html' ,context)

    elif request.method == 'POST':
        formUpdate = MovieForm(request.POST , request.FILES , instance=movieByid)
        if formUpdate.is_valid():
            formUpdate.save()
            return redirect('/')
    else:
        print(formUpdate.errors)
        context['form'] = formUpdate
        return render(request , 'edit.html' ,context)





def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

templates/add.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card my-5">
                <div class="card-body">
                    <h3 class="card-title mb-4">Add a New Movie</h3>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                         <div class="form-group">
                            {{form.as_p}}
                         </div>
                        <button type="submit" class="btn btn-primary">Add Movie</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie store
  </a>
</nav>
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--  <div class="container-fluid">-->
<!--    <a class="navbar-brand" href="/">-->
<!--      Movie App-->
<!--&lt;!&ndash;      <button class="btn btn-primary ms-2" onclick="location.href={% url 'movieapp:add_movie' %}">Add Movie</button>&ndash;&gt;-->
<!--      <a href="{% url 'movieapp:add_movie' %}" class="btn btn-primary ms-2">Add Movie</a>-->

<!--    </a>-->
<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="collapse navbar-collapse" id="navbarNav">-->
<!--      <ul class="navbar-nav">-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="/">Home</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->

{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}

{% block body %}
  <div class="container mt-5">
    <div class="alert alert-danger">
      <form method="POST">
        {%csrf_token%}
        <h3 class="text-center">did you want to delete the item??</h3>
        <div class="row justify-content-center">
          <input type="submit" class="btn btn-info" value="Delete">
        </div>
      </form>
    </div>
  </div>
{% endblock body %}
  

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}" width="300" height="300">

        </div>
        <div class="col-md-6">
            <h5 class="mb-3">Movie : {{movie.name}}</h5>
            <h5>Description:</h5>
            <h4 class="mb-3">{{movie.desc}}</h4>
            <h5 class="mb-3">Release Year: {{movie.year}}</h5>
            <h5 class="mb-3">Director : {{movie.director}}</h5>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}"> update </a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}"> delete </a>

        </div>


    </div>
</div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card my-5">
                <div class="card-body">
                    <h3 class="card-title mb-4">Update Movie</h3>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                         <div class="form-group">
                            {{form.as_p}}
                         </div>
                        <button type="submit" class="btn btn-primary">update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class=" mb-3">
  <a href="{% url 'movieapp:add_movie' %}" class="offset-md-2 btn btn-primary">Add Movie</a>
</div>
<div class="container">
  <div class="row w-100 p-0 w-0">
    
    {% for i in movie_list  %}
    <div class="col-lg-3 col-md-3 mb-4" >
    <div class="card mx-auto" style="width: 16rem; ">
      <img src="{{i.image.url}}" class="card-img-top" alt="..." height="240vh">
      <div class="card-body" >
        <h5 class="card-title">{{i.name}}</h5>
        <p class="card-text"><span class="text-mute font-weight-bold">Release Year : </span>{{i.year}}</p>
        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>
      </div>
    </div>
    
  </div>
  {% endfor %}
</div>
</div>

{% endblock %}